### ISSUE TITLE
What should I do to run it?

### ISSUE THREAD

**Issue by Seagullflysxt** [kseniaryabinova/KCF_and_kalman_filter#8]
Hi,I ran your codes in my vs2019,and then fixed some miscompatibles with the current version of opencv.
Now the bugs are all cleaned,but when I run it, **I only got :**
start to read gt files
start to run population
1 of 110
Then the programs stopped with  nothing else happens.
Please,pls tell me what to do  to run the code correctly :)

**Comment by sa1225** [comment]
I have the same question!!
And I also found that if I ran runtracker.cpp directly I would get results, but the prediction box was inaccurate from the start.

**Comment by kseniaryabinova** [comment]
Hi! Do you want to train it or just run pretrained kalman filter on some random video?

**Comment by sa1225** [comment]
> Hi! Do you want to train it or just run pretrained kalman filter on some random video?

Thank you for your reply. Now I have some specific dataset scenarios, so I need you to tell me how to train it.

**Comment by Seagullflysxt** [comment]
> Hi! Do you want to train it or just run pretrained kalman filter on some random video?
Yes,yes,thank for your reply :)
I'm runing it in some personal made videos, so I want to know how to train and run it.

Great thanks to you :)

**Comment by kseniaryabinova** [comment]
Hi! Just letting you know that I don't forget about this issue and I'm working on the solution right now

**Comment by kseniaryabinova** [comment]
Hello again!

I added an executable to be able to run on a webcam. You can easily modify it to run video from file. Just pass a path to a video in VideoCapture in runtracker.cpp

Also I fixed some problems with dataset reading in the train mode
Please refer [to this part of the readme](https://github.com/kseniaryabinova/KCF_and_kalman_filter#some-more-details) for more details

If you have any problems, let me know

**Comment by Seagullflysxt** [comment]
> 

Great thanks for your updates,the detailed description helped me a lot!
(Sorry for not replying you in time,I've been quit tracking projs for some days, transferd to another group,so kinda busy these days)
Big thanks again :P
